### PR TITLE
First pass documentation review

### PR DESCRIPTION
**Pull request by will-hart**
Hi toopay, as thanks for all your work I thought I'd take a quick look at some of the documentation, and so I've done a quick tidy up - this pull request!

No major changes, just reworded a few bits and added a couple of simple examples here and there.

I'm happy to put a bit of time into some more documentation - is there anywhere else you think would be helpful?

### CODE REVIEW

**Comment by toopay** [comment]
Excelent, thanks. I may add some disqus widget after this, so its more interactive with discussion in each section. I'll update the documentation tonight.

**Comment by will-hart** [comment]
OK, well let me know if there is anything in particular you want some extra hands on with the docs.

**Comment by flashover** [comment]
AAAaaaaaaah, you beat me to it! :D I was already working on this when a side project took more time than anticipated...

**Comment by will-hart** [comment]
Ah... sorry - I'm procrastinating :D

Was thinking of whipping up a basic example for the docs as well - see https://github.com/mecharius/gas-orm/blob/doc/example.  Feel free to team up if toopay is happy!

**Comment by flashover** [comment]
Looks good so far! It's still a WIP, right? As you mention a controller/view which are still to be included.

Maybe I'll give this all another try by the end of the week...

**Comment by toopay** [comment]
@mecharius @flashover Please do :octocat:

**Comment by flashover** [comment]
@mecharius: Maybe you can see if there's anything useful in the stuff I've already done: https://github.com/flashover/gas-orm/commit/491030b0fecc9ee3cdcec4141653d8d5066d5bc6

**Pull request merged**
